// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd9e09l5ZQm_Yc3VaTDKVm38IFM7f0Hg',
    appId: '1:1094427575499:web:c84307664036b799d2c74e',
    messagingSenderId: '1094427575499',
    projectId: 'arecommerce',
    authDomain: 'arecommerce.firebaseapp.com',
    storageBucket: 'arecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdSP9s2rS5fWN56rWLovQ46Sx51juYzU',
    appId: '1:1094427575499:android:a66c89273e14e87cd2c74e',
    messagingSenderId: '1094427575499',
    projectId: 'arecommerce',
    storageBucket: 'arecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YHe64QkSoHtBiV6wj1Ks5XuRlfGCyoM',
    appId: '1:1094427575499:ios:8a3394f4441d25bed2c74e',
    messagingSenderId: '1094427575499',
    projectId: 'arecommerce',
    storageBucket: 'arecommerce.appspot.com',
    androidClientId: '1094427575499-q2in3fsvdjmd4q5c16ff9ik6jj4jucoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.arEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YHe64QkSoHtBiV6wj1Ks5XuRlfGCyoM',
    appId: '1:1094427575499:ios:31f1ea98cb19b499d2c74e',
    messagingSenderId: '1094427575499',
    projectId: 'arecommerce',
    storageBucket: 'arecommerce.appspot.com',
    androidClientId: '1094427575499-q2in3fsvdjmd4q5c16ff9ik6jj4jucoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.arEcommerce.RunnerTests',
  );
}
